apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
        - name: result-container
          image: "ugougo05/result:latest"
          ports:
            - containerPort: 80
          env:
            - name: PG_HOST
              value: "postgres-service"
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: "postgres"
            - name: PG_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_USER
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: POSTGRES_PASSWORD
