apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker-container
        # Replace with your Docker Hub (or other registry) image
        image: ugougo05/worker:latest
        ports:
          - containerPort: 80
  env:
  - name: REDIS_HOST
    value: "redis-service"
  - name: DB_HOST
    value: "postgres-service"         # Update to your actual service name
  - name: DB_USERNAME
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: POSTGRES_USER             # Ensure secret key matches
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: db-credentials
        key: POSTGRES_PASSWORD         # Ensure secret key matches
  - name: DB_NAME
    value: "postgres"                 # Or change if needed
  - name: REDIS_HOST
    value: "redis-service" 
